### ISSUE TITLE
[env] 배포 환경 구축

### ISSUE THREAD

**Issue by yujiseok** [kdt-final-3/salarying-fe#10]
## 작업 상세 내용

- [x] 기존 `netlify`를 사용하기로 했는데, `AWS Amplify`는 어떨지?

**Comment by yujiseok** [comment]
## netlify
- 깃허브와 연동이 되어 정적서버를 통해 쉽게 호스팅 해줌
- 간단하다는 장점
- 빠른 시간 내에 배포 가능 (배포 자동화)
- 새로고침시 404에러를 해결 하기 위해 
  - public 디렉터리에 `__redirects` 파일을 생성해야한다. -> 리액트의 경우 SPA여서 정해진 자원(URL에 맞는 `HTML`)이 없기 때문
  - 해결하기 위해  _redirects 파일에 `/* /index.html 200`를 추가

--- 

## AWS Amplify
- SPA, 웹 애플리케이션 구축, 배포, 호스팅하기 위한 깃 기반의 `CI/CD` 제공
- 코드가 커밋될 때마다 업데이트 후 자동 배포
- 빌드가 실패하더라도 이전 버전 빌드 유지
- 배포 과정이 매우 간단함 
- S3, CloudFront 기반으로 동작
- 커스텀 도메인 사용가능

**Comment by yujiseok** [comment]
## vercel
- 개인적으로 vercel로 배포하고 싶지만, vercel의 경우 org 레포는 과금
- 이전 프로젝트에 포크한 레포를 깃액션을 통해 시간마다 pull 하여 싱크를 맞춰 배포
  - 바로 확인 못하는 단점
  - 생각보다 번거로움

**Comment by hyorimcho** [comment]
아무래도 과금 문제가 있는 두 가지 서비스 보다는 netlify 를 쓰는 것이 좋아보입니다. 
여태 org 레포에 배포하면서 딱히 큰 불편함도 못느꼈고요!
각 배포 서비스에 대해 깔끔하게 설명 잘 해 주셔서 파악하기 좋았습니다 감사합니다👍🏻
