### ISSUE TITLE
[bug] Disable husky in CI

### ISSUE THREAD

**Issue by yujiseok** [kdt-final-3/salarying-fe#28]
## 작업 상세 내용

- [x] 배포시 husky 에러 해결하기

## 참고 사항

Husky는 `prepare: husky install` 스크립트를 추천하는데, 이 스크립트에는 깃 훅이 항상 설치 되어야 하는 문제가 있다. 
즉 넷리파이의 캐시된 빌드시  깃 훅을 캐시하므로 비활성화 시켜야함

가장 쉬운 방법은 `is-ci`를 [추가](https://typicode.github.io/husky/#/?id=with-is-ci)하는 방법
```bash
npm install is-ci --save-dev
```

```json
{
  "scripts": {
    "prepare": "is-ci || husky install"
  }
}
```

`is-ci`가 무엇인지 모르지만, 일단 에러를 잡기 위해 추가 해보는 쪽으로

---
출처
- https://answers.netlify.com/t/error-when-building-a-react-app-that-has-husky-installed/54344/3
- https://typicode.github.io/husky/#/?id=disable-husky-in-cidockerprod

**Comment by yujiseok** [comment]
is-ci
- Returns `true` if the current environment is a Continuous Integration server.

**Comment by hyorimcho** [comment]
깃 훅이 항상 설치 되어야 하는 것이 문제라면  `prepare` 대신 `postinstall ` 스크립트로 한 번 바꿔서 설정 해보시는건 어떨까요?

**Comment by yujiseok** [comment]
해결완

https://github.com/kdt-final-3/salarying-fe/pull/29#issuecomment-1482907246
