### ISSUE TITLE
[env] 디자인 `tailwind.config.cjs`에 추가

### ISSUE THREAD

**Issue by yujiseok** [kdt-final-3/salarying-fe#40]
## 작업 상세 내용

- [x] 디자인 나올 시, 설정에 값들 추가하기

## 참고 사항

- `daisyUI`에도 추가할지
- 네이밍은 어떻게할지

**Comment by hyorimcho** [comment]
저번에 짧게 논의한대로 `gray-20`, `gray-30` 등등 `컬러명-진하기` 로 나타내면 될까요😀?
daisyUI에도 추가하는게 편하지 않을까 싶습니다.

**Comment by yujiseok** [comment]
@hyorimcho 
넵 근데 기존 tailwind 클래스명이랑 겹칠 수 도 있어서 앞에 프리픽스를 정하면 좋을 거 같아서요
